export const ADMIN_ROUTES = {
  DASHBOARD: '/admin',
  PROFILE: '/admin/profile',
  UPDATE_PROFILE: '/admin/profile/update',
  CHANGE_PASSWORD: '/admin/profile/change-password',
  USER_MANAGEMENT: '/admin/users',
  PARTNER_APPROVAL: '/admin/partners',
  TOUR_MODERATION: '/admin/tours',
  ADMIN_TOUR_DETAIL: (id: string | number = ':id') => `/admin/tours/${id}`,
  CATEGORY_MANAGEMENT: '/admin/categories',
  TICKET_TYPE_MANAGEMENT: '/admin/ticket-types',
  SYSTEM_VOUCHERS: '/admin/vouchers',
  CREATE_ADMIN_VOUCHER: '/admin/vouchers/create',
  ADMIN_VOUCHER_DETAIL: (id: string | number = ':id') => `/admin/vouchers/${id}`,
  EDIT_ADMIN_VOUCHER: (id: string | number = ':id') => `/admin/vouchers/${id}/edit`,
  DELETE_ADMIN_VOUCHER: (id: string | number = ':id') => `/admin/vouchers/${id}/delete`,
  WITHDRAWALS: '/admin/withdrawals',
  BANNER_MANAGEMENT: '/admin/banners',
  TOURISM_INFORMATION_MANAGEMENT: '/admin/tourism-information',
  CREATE_TOURISM_INFORMATION: '/admin/tourism-information/create',
  TOURISM_INFORMATION_DETAIL: (id: string | number = ':id') => `/admin/tourism-information/${id}`,
  EDIT_TOURISM_INFORMATION: (id: string | number = ':id') => `/admin/tourism-information/${id}/edit`,
  REPORT_MODERATION: '/admin/reports',
  CUSTOMER_ANALYTICS: '/admin/customer-analytics',
  PLATFORM_ANALYTICS: '/admin/platform-analytics',
  BOOKING_STATISTICS: '/admin/booking-statistics',
  REVENUE_STATISTICS: '/admin/revenue-statistics',
  SYSTEM_SETTINGS: '/admin/settings',
  AI_CONSOLE: '/admin/ai',

  // Dynamic Routes & Delete Confirms
  DELETE_CATEGORY: (id: string | number = ':id') => `/admin/categories/${id}/delete`,
  DELETE_BANNER: (id: string | number = ':id') => `/admin/banners/${id}/delete`,
  CREATE_USER: '/admin/users/create',
  EDIT_USER: (id: string | number = ':id') => `/admin/users/${id}/edit`,
  DELETE_USER: (id: string | number = ':id') => `/admin/users/${id}/delete`,
} as const;
